---
# tasks file for mysql
- name: Specify MySQL root password before installing
  debconf:
    name: mysql-server
    question: mysql-server/root_password
    value: "{{ DB_PASSWORD }}"
    vtype: password
  become: yes

- name: Confirm MySQL root password before installing
  debconf:
    name: mysql-server
    question: mysql-server/root_password_again
    value: "{{ DB_PASSWORD }}"
    vtype: password
  become: yes

- name: Install MySQL and other dependencies
  apt:
    name: ['mysql-server', 'python3-mysqldb']
    state: present
  become: yes